2025-04-03 18:15:17,645 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 18:15:17,646 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 18:15:17,646 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 18:15:17,647 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:15:17,647 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:15:17,647 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:15:17,929 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 18:15:17,929 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 18:15:17,930 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 18:15:17,930 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:15:17,930 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:15:17,930 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:03,754 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 18:27:03,754 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 18:27:03,755 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 18:27:03,755 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:03,755 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:03,755 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:04,034 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 18:27:04,035 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 18:27:04,035 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 18:27:04,035 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:04,036 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 18:27:04,036 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:04,844 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 21:20:04,846 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 21:20:04,847 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 21:20:04,848 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:04,848 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:04,848 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:05,386 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 21:20:05,387 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 21:20:05,388 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 21:20:05,388 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:05,388 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:20:05,389 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,054 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 21:31:05,054 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 21:31:05,055 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 21:31:05,055 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,056 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,056 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,393 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 21:31:05,394 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 21:31:05,394 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 21:31:05,395 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,395 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 21:31:05,395 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:09,984 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 22:18:09,984 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 22:18:09,985 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 22:18:09,985 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:09,985 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:09,985 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:10,254 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 22:18:10,254 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 22:18:10,255 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 22:18:10,255 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:10,255 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:18:10,255 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 22:19:42,642 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-03 22:19:42,676 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-03 22:19:43,257 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-03 23:17:02,551 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 23:17:02,551 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 23:17:02,552 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 23:17:02,552 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:17:02,552 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:17:02,552 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:17:02,806 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-03 23:17:02,806 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-03 23:17:02,807 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-03 23:17:02,807 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:17:02,807 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:17:02,807 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-03 23:20:26,929 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.reaction_time [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.reaction_time
2025-04-04 11:21:48,310 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:21:48,313 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:21:48,315 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:21:48,315 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:21:48,315 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:21:48,315 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:21:48,593 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:21:48,594 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:21:48,594 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:21:48,594 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:21:48,595 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:21:48,595 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:24:31,498 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-04 11:32:56,024 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:32:56,024 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:32:56,025 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:32:56,025 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:32:56,025 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:32:56,025 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:32:56,291 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:32:56,292 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:32:56,292 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:32:56,292 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:32:56,292 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:32:56,293 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:35:40,420 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:35:40,421 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:35:40,422 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:35:40,423 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:35:40,423 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:35:40,424 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,429 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:41:25,430 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:41:25,431 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:41:25,431 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,431 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,431 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,697 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:41:25,697 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:41:25,698 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:41:25,698 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,698 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:41:25,698 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:44:27,344 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.reaction_time [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.reaction_time
2025-04-04 11:48:37,249 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:48:37,250 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:48:37,250 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:48:37,251 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:37,251 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:37,251 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:37,515 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 11:48:37,516 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 11:48:37,516 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 11:48:37,517 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:37,517 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:37,517 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 11:48:46,718 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.reaction_time [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.reaction_time
2025-04-04 11:49:19,482 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.reaction_time [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:285]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 262, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.reaction_time
2025-04-04 20:01:25,014 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 20:01:25,014 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 20:01:25,015 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 20:01:25,015 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:01:25,015 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:01:25,015 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:01:25,350 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-04 20:01:25,351 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-04 20:01:25,352 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-04 20:01:25,352 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:01:25,353 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:01:25,353 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:347]
2025-04-04 20:10:53,173 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:10:53,174 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:10:53,174 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:10:53,174 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:10:53,174 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:10:53,175 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:10:53,465 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:10:53,466 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:10:53,466 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:10:53,466 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:10:53,466 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:10:53,467 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:52,796 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:15:52,797 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:15:52,797 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:15:52,797 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:52,798 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:52,798 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:53,111 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:15:53,111 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:15:53,112 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:15:53,112 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:53,112 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:15:53,112 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:363]
2025-04-04 20:16:37,707 ERROR: 数据库错误: NOT NULL constraint failed: stroop_results.reaction_time [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:291]
2025-04-04 20:25:02,574 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:25:02,575 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:25:02,575 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:25:02,575 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:02,576 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:02,576 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:02,843 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:25:02,844 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:25:02,844 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:25:02,845 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:02,845 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:02,845 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:25:45,422 INFO: Received data: [{'group': 1, 'trial': 1, 'word': '红', 'color': 'purple', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 653, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:12.273Z'}, {'group': 1, 'trial': 2, 'word': '黄', 'color': 'green', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 608, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:13.930Z'}, {'group': 1, 'trial': 3, 'word': '红', 'color': 'red', 'isConsistent': True, 'response': 'no_response', 'reactionTime': None, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:15.552Z'}, {'group': 1, 'trial': 4, 'word': '红', 'color': 'red', 'isConsistent': True, 'response': 'consistent', 'reactionTime': 553, 'isCorrect': True, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:18.059Z'}, {'group': 1, 'trial': 5, 'word': '橙', 'color': 'yellow', 'isConsistent': False, 'response': 'no_response', 'reactionTime': None, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:19.619Z'}, {'group': 2, 'trial': 1, 'word': '绿', 'color': 'yellow', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 905, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:26.103Z'}, {'group': 2, 'trial': 2, 'word': '红', 'color': 'red', 'isConsistent': True, 'response': 'consistent', 'reactionTime': 1072, 'isCorrect': True, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:28.012Z'}, {'group': 2, 'trial': 3, 'word': '黄', 'color': 'blue', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 351, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:30.089Z'}, {'group': 2, 'trial': 4, 'word': '黄', 'color': 'blue', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 413, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:31.454Z'}, {'group': 2, 'trial': 5, 'word': '蓝', 'color': 'yellow', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 306, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:32.869Z'}, {'group': 3, 'trial': 1, 'word': '紫', 'color': 'blue', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 606, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:37.551Z'}, {'group': 3, 'trial': 2, 'word': '橙', 'color': 'green', 'isConsistent': False, 'response': 'inconsistent', 'reactionTime': 900, 'isCorrect': True, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:39.157Z'}, {'group': 3, 'trial': 3, 'word': '绿', 'color': 'green', 'isConsistent': True, 'response': 'consistent', 'reactionTime': 505, 'isCorrect': True, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:41.068Z'}, {'group': 3, 'trial': 4, 'word': '橙', 'color': 'blue', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 277, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:42.588Z'}, {'group': 3, 'trial': 5, 'word': '黄', 'color': 'orange', 'isConsistent': False, 'response': 'consistent', 'reactionTime': 538, 'isCorrect': False, 'userId': 'anonymous', 'timestamp': '2025-04-04T12:25:43.875Z'}] [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:245]
2025-04-04 20:25:45,422 ERROR: Unexpected error: float() argument must be a string or a real number, not 'NoneType' [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:306]
2025-04-04 20:26:07,146 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:26:07,147 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:26:07,147 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:26:07,148 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:26:07,148 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:26:07,148 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:26:07,436 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:26:07,437 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:26:07,437 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:26:07,437 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:26:07,438 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:26:07,438 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,204 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:47:53,205 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:47:53,205 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:47:53,205 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,206 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,206 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,456 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:47:53,457 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:47:53,457 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:47:53,457 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,458 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:47:53,458 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:07,742 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:48:07,742 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:48:07,743 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:48:07,743 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:07,743 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:07,743 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:08,004 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 20:48:08,004 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 20:48:08,005 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 20:48:08,005 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:08,005 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 20:48:08,005 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:370]
2025-04-04 23:22:50,676 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 23:22:50,677 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 23:22:50,678 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 23:22:50,678 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-04 23:22:50,678 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-04 23:22:50,678 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-04 23:22:50,958 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-04 23:22:50,959 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-04 23:22:50,959 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-04 23:22:50,959 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-04 23:22:50,959 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-04 23:22:50,960 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:13,817 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-05 10:49:13,819 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-05 10:49:13,820 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-05 10:49:13,820 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:13,821 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:13,821 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:14,180 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:69]
2025-04-05 10:49:14,181 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:97]
2025-04-05 10:49:14,181 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:124]
2025-04-05 10:49:14,181 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:14,182 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:49:14,182 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:346]
2025-04-05 10:58:25,777 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 10:58:25,778 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 10:58:25,779 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 10:58:25,779 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 10:58:25,780 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 10:58:25,780 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 10:58:26,092 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 10:58:26,093 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 10:58:26,093 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 10:58:26,094 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 10:58:26,094 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 10:58:26,094 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,127 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 11:15:28,127 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 11:15:28,128 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 11:15:28,128 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,128 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,128 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,403 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 11:15:28,404 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 11:15:28,404 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 11:15:28,404 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,404 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:15:28,405 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,402 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 11:34:15,403 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 11:34:15,404 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 11:34:15,404 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,404 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,404 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,726 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 11:34:15,727 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 11:34:15,727 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 11:34:15,727 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,727 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:34:15,728 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 11:59:01,675 INFO: Database initialized successfully: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,681 INFO: Database initialized successfully: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,685 INFO: Database initialized successfully: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,685 INFO: Database connection successful: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:01,686 INFO: Database connection successful: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:01,687 INFO: Database connection successful: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:01,982 INFO: Database initialized successfully: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,983 INFO: Database initialized successfully: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,983 INFO: Database initialized successfully: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:47]
2025-04-05 11:59:01,984 INFO: Database connection successful: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:01,984 INFO: Database connection successful: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:01,984 INFO: Database connection successful: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:277]
2025-04-05 11:59:07,493 ERROR: Login failed: Could not build url for endpoint 'navigation'. Did you mean 'static' instead? [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:167]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 162, in login
    'redirect': url_for('navigation')
                ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'navigation'. Did you mean 'static' instead?
2025-04-05 11:59:11,004 ERROR: Login failed: Could not build url for endpoint 'navigation'. Did you mean 'static' instead? [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:167]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 162, in login
    'redirect': url_for('navigation')
                ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'navigation'. Did you mean 'static' instead?
2025-04-05 12:00:50,969 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:00:50,970 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:00:50,970 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:00:50,970 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:00:50,970 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:00:50,971 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:00:51,272 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:00:51,273 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:00:51,273 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:00:51,273 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:00:51,273 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:00:51,274 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,653 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:06:35,653 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:06:35,654 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:06:35,654 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,654 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,654 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,965 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:06:35,965 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:06:35,966 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:06:35,966 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,966 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:06:35,967 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:52,738 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:31:52,739 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:31:52,739 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:31:52,739 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:52,740 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:52,740 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:53,033 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:31:53,034 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:31:53,034 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:31:53,034 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:53,035 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:31:53,035 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,106 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:36:36,106 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:36:36,107 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:36:36,107 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,107 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,107 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,397 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:36:36,397 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:36:36,398 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:36:36,398 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,398 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:36:36,398 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,059 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:38:30,060 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:38:30,060 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:38:30,061 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,061 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,061 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,345 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 12:38:30,345 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 12:38:30,345 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 12:38:30,346 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,346 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 12:38:30,346 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:28,872 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 13:44:28,873 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 13:44:28,873 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 13:44:28,874 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:28,874 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:28,874 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:29,149 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 13:44:29,149 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 13:44:29,150 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 13:44:29,150 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:29,150 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:44:29,150 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,696 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 13:47:25,697 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 13:47:25,697 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 13:47:25,697 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,698 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,698 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,975 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-05 13:47:25,976 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-05 13:47:25,976 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-05 13:47:25,976 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,977 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-05 13:47:25,977 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:46,735 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-06 11:03:46,736 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-06 11:03:46,736 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-06 11:03:46,736 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:46,737 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:46,737 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:47,027 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-06 11:03:47,027 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-06 11:03:47,027 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-06 11:03:47,028 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:47,028 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-06 11:03:47,028 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:36,578 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-07 21:10:36,579 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-07 21:10:36,579 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-07 21:10:36,580 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:36,580 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:36,580 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:37,046 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-07 21:10:37,047 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-07 21:10:37,048 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-07 21:10:37,048 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:37,049 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-07 21:10:37,049 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,286 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-08 17:36:47,289 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-08 17:36:47,290 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-08 17:36:47,290 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,291 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,291 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,581 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-08 17:36:47,582 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-08 17:36:47,582 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-08 17:36:47,582 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,582 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 17:36:47,582 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:37:18,620 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:37:18,620 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:37:18,621 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:37:18,621 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:37:18,861 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:37:18,861 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:37:18,862 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:37:18,862 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:38:19,428 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:38:19,429 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:38:19,429 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:38:19,429 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:38:19,694 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:38:19,695 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:38:19,695 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:38:19,695 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:39:11,280 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:39:11,281 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:39:11,281 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:39:11,281 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:39:11,547 INFO: 用户数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:62]
2025-04-08 18:39:11,548 INFO: 实验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:88]
2025-04-08 18:39:11,548 INFO: 注意力测验数据库初始化成功 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:113]
2025-04-08 18:39:11,548 INFO: 所有数据库初始化完成 [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:341]
2025-04-08 18:39:27,194 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-08 18:39:27,194 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-08 18:39:27,195 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-08 18:39:27,195 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:39:27,195 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:39:27,195 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:39:27,459 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:70]
2025-04-08 18:39:27,459 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:98]
2025-04-08 18:39:27,460 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:125]
2025-04-08 18:39:27,460 INFO: 数据库连接正常: user_db (database.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:39:27,460 INFO: 数据库连接正常: experiment_db (database2.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-08 18:39:27,460 INFO: 数据库连接正常: attention_db (database3.db) [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:353]
2025-04-12 11:41:10,661 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 11:41:10,663 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 11:41:10,664 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 11:41:10,664 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:41:10,664 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:41:10,665 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:41:16,767 ERROR: 登录失败: no such column: password_hash [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:216]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 198, in login
    cursor.execute(
    ~~~~~~~~~~~~~~^
        '''SELECT id, password_hash FROM users
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        WHERE username = ? AND activation_code = ?''',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (username, activation_code)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
sqlite3.OperationalError: no such column: password_hash
2025-04-12 11:41:40,189 ERROR: 登录失败: no such column: password_hash [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:216]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 198, in login
    cursor.execute(
    ~~~~~~~~~~~~~~^
        '''SELECT id, password_hash FROM users
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        WHERE username = ? AND activation_code = ?''',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (username, activation_code)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
sqlite3.OperationalError: no such column: password_hash
2025-04-12 11:45:47,476 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 11:45:47,480 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 11:45:47,484 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 11:45:47,485 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:45:47,486 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:45:47,487 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:45:51,343 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 11:45:51,344 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 11:45:51,344 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 11:45:51,344 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:45:51,344 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 11:45:51,345 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:08:16,544 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 12:08:16,545 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 12:08:16,545 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 12:08:16,545 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:08:16,546 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:08:16,546 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:09:49,197 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 12:09:49,198 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 12:09:49,198 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 12:09:49,198 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:09:49,199 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:09:49,199 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:15:12,089 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 12:15:12,090 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 12:15:12,090 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 12:15:12,090 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:15:12,091 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:15:12,091 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:17:45,307 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 12:17:45,307 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 12:17:45,308 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 12:17:45,308 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:17:45,308 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:17:45,308 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:33:07,043 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 12:33:07,043 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-04-12 12:33:07,044 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:160]
2025-04-12 12:33:07,044 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:33:07,044 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 12:33:07,044 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:418]
2025-04-12 15:40:57,633 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 15:40:57,635 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 15:40:57,636 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-04-12 15:40:57,637 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:40:57,637 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:40:57,637 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:51:33,620 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 15:51:33,620 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 15:51:33,620 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-04-12 15:51:33,621 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:51:33,621 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:51:33,621 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:416]
2025-04-12 15:54:26,116 ERROR: 提交实验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:351]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 328, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-04-12 15:56:38,434 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 15:56:38,435 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 15:56:38,435 ERROR: 注意力测验数据库初始化失败: near ")": syntax error [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:159]
2025-04-12 15:56:38,435 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 15:56:38,435 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 15:56:38,436 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 15:57:28,882 ERROR: 提交实验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:350]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 327, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-04-12 16:03:28,360 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 16:03:28,363 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 16:03:28,364 ERROR: 注意力测验数据库初始化失败: near ")": syntax error [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:159]
2025-04-12 16:03:28,364 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:03:28,365 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:03:28,365 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:06:23,382 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:350]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 327, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-12 16:17:20,833 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 16:17:20,833 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 16:17:20,833 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-04-12 16:17:20,834 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:17:20,834 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:17:20,834 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:18:46,485 ERROR: 提交实验数据失败: NOT NULL constraint failed: stroop_results.response [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:350]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 327, in submit_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO stroop_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.IntegrityError: NOT NULL constraint failed: stroop_results.response
2025-04-12 16:44:09,076 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 16:44:09,077 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 16:44:09,077 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-04-12 16:44:09,078 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:44:09,078 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 16:44:09,078 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 17:09:42,000 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-04-12 17:09:42,000 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-04-12 17:09:42,001 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-04-12 17:09:42,001 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 17:09:42,001 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-04-12 17:09:42,001 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:32:10,676 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 10:32:10,677 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 10:32:10,677 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 10:32:10,677 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:32:10,677 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:32:10,678 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:44:50,548 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 10:44:50,549 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 10:44:50,549 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 10:44:50,549 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:44:50,549 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 10:44:50,550 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:09:10,813 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:09:10,815 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:09:10,817 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:09:10,817 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:09:10,817 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:09:10,818 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:14:41,187 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:14:41,188 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:14:41,188 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:14:41,189 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:14:41,189 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:14:41,189 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:17:07,122 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:17:07,123 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:17:07,124 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:17:07,124 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:17:07,124 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:17:07,124 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:22:12,988 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:22:12,992 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:22:12,992 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:22:12,992 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:22:12,994 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:22:12,994 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:27:17,106 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:27:17,107 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:27:17,107 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:27:17,107 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:27:17,108 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:27:17,108 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:31:28,943 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:31:28,944 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:31:28,944 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:31:28,944 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:31:28,945 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:31:28,945 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:34:44,374 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:34:44,375 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:34:44,375 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:34:44,375 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:34:44,375 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:34:44,376 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:36:06,914 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:36:06,915 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:36:06,915 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:36:06,915 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:36:06,916 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:36:06,916 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:52:02,733 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 18:52:02,733 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 18:52:02,734 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 18:52:02,734 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:52:02,734 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 18:52:02,734 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:20:19,343 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:20:19,344 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:20:19,344 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:20:19,344 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:20:19,345 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:20:19,345 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:24:02,945 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:24:02,946 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:24:02,946 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:24:02,946 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:24:02,947 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:24:02,947 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:09,007 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:29:09,007 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:29:09,008 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:29:09,008 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:09,008 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:09,009 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:43,260 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:29:43,261 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:29:43,261 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:29:43,261 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:43,262 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:29:43,262 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:30:20,274 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:30:20,274 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:30:20,274 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:30:20,275 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:30:20,275 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:30:20,275 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:34:03,714 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:34:03,715 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:34:03,715 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:34:03,715 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:34:03,715 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:34:03,716 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:50:35,985 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:50:35,985 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:50:35,986 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:50:35,986 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:50:35,986 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:50:35,986 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:51:31,284 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:51:31,285 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:51:31,285 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:51:31,286 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:51:31,286 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:51:31,286 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:54:47,723 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:54:47,723 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:54:47,723 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:54:47,724 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:54:47,724 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:54:47,724 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:58:42,921 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 22:58:42,921 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 22:58:42,922 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 22:58:42,922 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:58:42,922 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 22:58:42,922 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 23:09:21,251 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-06 23:09:21,252 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-06 23:09:21,252 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-06 23:09:21,253 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 23:09:21,253 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-06 23:09:21,253 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 09:37:07,830 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 09:37:07,831 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 09:37:07,831 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 09:37:07,831 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 09:37:07,832 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 09:37:07,832 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:42:24,027 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 17:42:24,030 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 17:42:24,031 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 17:42:24,032 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:42:24,032 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:42:24,032 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:49:33,964 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 17:49:33,965 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 17:49:33,965 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 17:49:33,965 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:49:33,965 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 17:49:33,966 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:21:37,095 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 18:21:37,099 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 18:21:37,100 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 18:21:37,100 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:21:37,102 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:21:37,102 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:22:59,553 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 18:22:59,556 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 18:22:59,557 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 18:22:59,557 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:22:59,559 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:22:59,559 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:27:47,661 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 18:27:47,665 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 18:27:47,666 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 18:27:47,666 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:27:47,667 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:27:47,668 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:28:34,706 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-09 18:28:34,707 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-09 18:28:34,707 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-09 18:28:34,708 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:28:34,708 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-09 18:28:34,708 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:415]
2025-05-10 21:48:27,647 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-10 21:48:27,649 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-10 21:48:27,650 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-10 21:48:27,650 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-10 21:48:27,651 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-10 21:48:27,651 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:45:45,221 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-11 22:45:45,222 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-11 22:45:45,222 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-11 22:45:45,223 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:45:45,223 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:45:45,223 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:49:02,053 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-11 22:49:02,054 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-11 22:49:02,054 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:157]
2025-05-11 22:49:02,055 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:49:02,055 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:49:02,055 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-11 22:52:53,226 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-11 22:52:53,227 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-11 22:52:53,227 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-11 22:52:53,227 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:52:53,228 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:52:53,228 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:56:40,517 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-11 22:56:40,517 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-11 22:56:40,518 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-11 22:56:40,518 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:56:40,518 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:56:40,519 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:57:05,237 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-11 22:57:05,238 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-11 22:57:05,239 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-11 22:57:05,240 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:57:05,240 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 22:57:05,241 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:12:56,199 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-11 23:12:56,199 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-11 23:12:56,200 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-11 23:12:56,200 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:12:56,200 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:12:56,200 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:13:32,270 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-11 23:13:32,271 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-11 23:13:32,271 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-11 23:13:32,271 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:13:32,271 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-11 23:13:32,272 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-12 16:35:13,888 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-12 16:35:13,889 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-12 16:35:13,889 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-12 16:35:13,890 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-12 16:35:13,890 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-12 16:35:13,890 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 10:06:04,677 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 10:06:04,678 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 10:06:04,678 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 10:06:04,679 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 10:06:04,679 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 10:06:04,679 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 12:18:42,027 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 12:18:42,028 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 12:18:42,029 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 12:18:42,029 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 12:18:42,029 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 12:18:42,030 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 12:23:37,114 ERROR: Exception on /navigation [GET] [in C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 57, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 228, in navigation
    return render_template('navigation.html')
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\21502\PycharmProjects\PythonProject3\templates\navigation.html", line 575, in top-level template code
    <a href="{{ url_for('examination') }}" data-quiz="examination1" class="quiz-link">测试一</a>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\21502\PycharmProjects\PythonProject3\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'examination'. Did you mean 'examination1' instead?
2025-05-13 17:09:10,580 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 17:09:10,582 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 17:09:10,583 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 17:09:10,583 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:09:10,584 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:09:10,584 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:11:29,755 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 17:11:29,755 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 17:11:29,755 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 17:11:29,756 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:11:29,756 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:11:29,756 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:17:46,107 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 17:17:46,108 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 17:17:46,108 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 17:17:46,108 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:17:46,108 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 17:17:46,109 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:01:03,035 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 22:01:03,038 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 22:01:03,040 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 22:01:03,040 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:01:03,040 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:01:03,040 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:04:26,356 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-13 22:04:26,357 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-13 22:04:26,357 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-13 22:04:26,357 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:04:26,358 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-13 22:04:26,358 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:27:04,268 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 14:27:04,273 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 14:27:04,276 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 14:27:04,277 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:27:04,277 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:27:04,278 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:58:41,666 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 14:58:41,667 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 14:58:41,667 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 14:58:41,667 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:58:41,667 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 14:58:41,668 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 17:59:20,573 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 17:59:20,575 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 17:59:20,575 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 17:59:20,575 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 17:59:20,576 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 17:59:20,576 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:02:19,977 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 18:02:19,978 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 18:02:19,978 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 18:02:19,978 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:02:19,978 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:02:19,979 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:11:20,452 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 18:11:20,453 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 18:11:20,454 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 18:11:20,454 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:11:20,454 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:11:20,455 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:28:45,891 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 18:28:45,891 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 18:28:45,892 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 18:28:45,892 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:28:45,892 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 18:28:45,892 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:09:27,677 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 23:09:27,679 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 23:09:27,680 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 23:09:27,681 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:09:27,681 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:09:27,681 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:36:12,424 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 23:36:12,425 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 23:36:12,425 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 23:36:12,426 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:36:12,426 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:36:12,426 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:37:35,834 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-14 23:37:35,835 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-14 23:37:35,835 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-14 23:37:35,835 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:37:35,835 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-14 23:37:35,836 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 00:53:52,894 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 00:53:52,895 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 00:53:52,896 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 00:53:52,896 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 00:53:52,897 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 00:53:52,897 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 09:54:29,463 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 09:54:29,463 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 09:54:29,464 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 09:54:29,464 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 09:54:29,464 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 09:54:29,464 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 10:42:14,353 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 10:42:14,353 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 10:42:14,354 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 10:42:14,354 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 10:42:14,354 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 10:42:14,354 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 10:52:02,022 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:107]
2025-05-15 10:52:02,023 INFO: Stroop实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:134]
2025-05-15 10:52:02,023 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:161]
2025-05-15 10:52:02,031 INFO: CPT实验数据库初始化成功: database4.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:202]
2025-05-15 10:52:02,031 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:579]
2025-05-15 10:52:02,031 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:579]
2025-05-15 10:52:02,032 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:579]
2025-05-15 10:52:02,033 INFO: 数据库连接正常: cpt_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:579]
2025-05-15 11:04:38,239 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:04:38,240 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:04:38,240 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:04:38,241 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:04:38,241 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:04:38,241 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:16:40,571 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:16:40,572 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:16:40,572 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:16:40,572 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:16:40,572 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:16:40,573 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:15,455 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:17:15,456 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:17:15,456 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:17:15,456 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:15,456 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:15,457 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:41,420 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:17:41,421 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:17:41,422 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:17:41,422 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:41,422 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:17:41,422 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:19:51,728 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:19:51,729 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:19:51,729 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:19:51,729 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:19:51,729 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:19:51,730 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:27:52,403 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:27:52,404 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:27:52,404 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:27:52,404 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:27:52,404 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:27:52,405 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:53:23,796 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:53:23,797 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:53:23,797 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:53:23,797 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:53:23,797 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:53:23,798 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:54:57,438 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 11:54:57,439 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 11:54:57,439 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 11:54:57,439 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:54:57,439 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 11:54:57,439 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 12:03:38,504 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 12:03:38,504 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 12:03:38,505 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 12:03:38,505 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 12:03:38,505 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 12:03:38,505 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:03:43,759 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:03:43,760 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:03:43,760 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:03:43,761 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:03:43,761 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:03:43,761 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:13:37,765 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:13:37,765 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:13:37,766 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:13:37,766 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:13:37,766 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:13:37,766 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:27:14,415 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:27:14,416 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:27:14,416 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:27:14,417 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:27:14,417 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:27:14,417 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:38:53,575 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:38:53,576 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:38:53,576 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:38:53,577 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:38:53,577 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:38:53,577 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:43:14,456 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:43:14,458 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:43:14,458 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:43:14,459 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:43:14,459 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:43:14,459 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:50:21,879 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 14:50:21,880 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 14:50:21,882 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 14:50:21,882 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:50:21,883 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 14:50:21,883 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:54:43,934 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 15:54:43,935 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 15:54:43,936 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 15:54:43,937 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:54:43,937 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:54:43,938 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:57:05,849 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 15:57:05,849 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 15:57:05,850 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 15:57:05,850 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:57:05,850 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 15:57:05,851 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:05:10,537 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 16:05:10,538 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 16:05:10,538 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 16:05:10,538 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:05:10,539 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:05:10,539 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:12:00,468 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 16:12:00,468 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 16:12:00,469 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 16:12:00,469 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:12:00,469 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 16:12:00,469 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:24:53,421 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 18:24:53,423 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 18:24:53,424 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 18:24:53,425 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:24:53,425 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:24:53,425 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:26:00,210 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:26:05,215 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:26:10,971 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:26:16,974 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:31:25,023 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 18:31:25,024 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 18:31:25,024 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 18:31:25,025 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:31:25,025 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:31:25,025 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:32:27,523 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:32:32,540 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:32:37,973 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:32:43,973 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:34:11,240 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 18:34:11,241 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 18:34:11,241 ERROR: 注意力测验数据库初始化失败: unrecognized token: "#" [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 18:34:11,242 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:420]
2025-05-15 18:34:11,242 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:420]
2025-05-15 18:34:11,242 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:420]
2025-05-15 18:35:19,257 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:403]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 381, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:35:24,274 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:403]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 381, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:35:29,975 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:403]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 381, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:35:35,966 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:403]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 381, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:36:17,967 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 18:36:17,968 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 18:36:17,968 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 18:36:17,969 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:36:17,969 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:36:17,969 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 18:37:40,887 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:37:45,970 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:37:51,965 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 18:37:57,959 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 19:54:49,374 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 19:54:49,375 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 19:54:49,375 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 19:54:49,375 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:54:49,375 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:54:49,376 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:55:51,322 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 19:55:51,322 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 19:55:51,323 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 19:55:51,323 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:55:51,323 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:55:51,323 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 19:57:01,226 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 19:57:06,235 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 19:57:11,244 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 19:57:16,254 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 20:03:54,387 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 20:03:54,388 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 20:03:54,388 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 20:03:54,389 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 20:03:54,389 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 20:03:54,389 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 20:04:51,173 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 20:04:56,194 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 20:05:01,200 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 21:19:40,443 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:19:40,444 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:19:40,445 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:19:40,445 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:19:40,445 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:19:40,445 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:31:24,379 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:31:24,380 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:31:24,381 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:31:24,381 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:31:24,381 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:31:24,382 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:33:01,112 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 21:33:06,221 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 21:33:11,236 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 21:33:16,970 ERROR: 提交注意力测验数据失败: no such table: main.users [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:405]
Traceback (most recent call last):
  File "C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py", line 383, in submit_attention_results
    cursor.executemany('''
    ~~~~~~~~~~~~~~~~~~^^^^
        INSERT INTO attention_results
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
        ) for trial in data
        ^^^^^^^^^^^^^^^^^^^
    ])
    ^^
sqlite3.OperationalError: no such table: main.users
2025-05-15 21:34:58,231 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:34:58,232 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:34:58,236 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:34:58,236 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:34:58,236 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:34:58,238 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:422]
2025-05-15 21:42:48,383 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:42:48,384 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:42:48,388 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:42:48,388 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:42:48,388 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:42:48,389 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:48:13,988 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:48:13,988 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:48:13,992 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:48:13,992 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:48:13,992 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:48:13,994 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:52:34,753 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:52:34,754 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:52:34,758 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:52:34,758 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:52:34,758 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:52:34,759 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:58:11,703 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:58:11,703 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:58:11,707 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:58:11,707 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:58:11,708 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:58:11,708 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:59:51,737 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-15 21:59:51,742 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-15 21:59:51,743 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-15 21:59:51,743 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:59:51,744 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-15 21:59:51,744 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:41:55,675 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 13:41:55,679 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 13:41:55,682 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 13:41:55,683 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:41:55,684 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:41:55,684 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:00,419 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 13:59:00,420 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 13:59:00,420 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 13:59:00,420 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:00,421 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:00,421 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:19,643 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 13:59:19,644 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 13:59:19,644 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 13:59:19,645 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:19,645 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:19,645 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:35,182 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 13:59:35,182 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 13:59:35,183 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 13:59:35,183 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:35,183 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 13:59:35,183 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:00:45,424 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 14:00:45,425 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 14:00:45,425 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 14:00:45,425 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:00:45,425 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:00:45,426 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:45:32,279 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 14:45:32,280 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 14:45:32,281 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 14:45:32,281 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:45:32,281 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:45:32,282 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:46:28,132 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 14:46:28,132 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 14:46:28,133 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 14:46:28,133 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:46:28,133 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:46:28,133 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:51:40,302 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 14:51:40,302 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 14:51:40,303 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 14:51:40,303 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:51:40,303 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 14:51:40,303 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:04:01,585 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 22:04:01,587 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 22:04:01,588 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 22:04:01,589 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:04:01,589 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:04:01,589 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:46:04,402 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 22:46:04,403 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 22:46:04,403 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 22:46:04,403 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:46:04,404 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:46:04,404 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:47:56,923 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 22:47:56,923 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 22:47:56,924 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 22:47:56,924 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:47:56,924 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 22:47:56,924 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 23:03:36,278 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-16 23:03:36,279 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-16 23:03:36,279 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-16 23:03:36,280 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 23:03:36,280 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-16 23:03:36,280 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:29:34,001 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-17 21:29:34,003 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-17 21:29:34,004 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-17 21:29:34,004 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:29:34,005 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:29:34,005 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:31:26,313 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-17 21:31:26,313 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-17 21:31:26,313 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-17 21:31:26,314 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:31:26,314 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:31:26,314 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:36:20,554 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-17 21:36:20,554 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-17 21:36:20,555 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-17 21:36:20,555 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:36:20,555 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-17 21:36:20,555 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-18 15:07:21,012 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-18 15:07:21,015 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-18 15:07:21,016 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-18 15:07:21,017 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-18 15:07:21,017 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-18 15:07:21,017 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-19 20:38:21,737 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-19 20:38:21,742 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-19 20:38:21,744 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-19 20:38:21,744 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-19 20:38:21,744 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-19 20:38:21,745 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:47:47,359 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-20 10:47:47,363 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-20 10:47:47,365 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-20 10:47:47,365 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:47:47,365 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:47:47,365 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:51:59,395 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-20 10:51:59,396 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-20 10:51:59,396 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-20 10:51:59,396 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:51:59,396 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 10:51:59,397 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:26:45,012 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-20 18:26:45,014 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-20 18:26:45,016 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-20 18:26:45,016 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:26:45,016 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:26:45,016 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:40:48,405 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:106]
2025-05-20 18:40:48,405 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:133]
2025-05-20 18:40:48,406 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-20 18:40:48,406 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:40:48,406 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 18:40:48,406 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:423]
2025-05-20 23:00:37,054 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-20 23:00:37,055 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-20 23:00:37,056 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-20 23:00:37,056 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-20 23:00:37,056 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-20 23:00:37,056 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 00:35:17,690 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-21 00:35:17,690 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-21 00:35:17,690 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-21 00:35:17,691 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 00:35:17,691 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 00:35:17,691 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:35:01,501 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-21 13:35:01,502 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-21 13:35:01,504 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-21 13:35:01,504 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:35:01,504 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:35:01,504 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:40:26,365 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-21 13:40:26,365 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-21 13:40:26,366 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-21 13:40:26,366 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:40:26,366 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 13:40:26,366 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:12:02,282 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-21 19:12:02,283 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-21 19:12:02,283 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-21 19:12:02,283 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:12:02,283 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:12:02,284 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:16:06,964 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-21 19:16:06,964 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-21 19:16:06,964 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-21 19:16:06,965 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:16:06,965 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-21 19:16:06,965 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:17:55,314 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-22 14:17:55,315 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-22 14:17:55,316 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-22 14:17:55,317 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:17:55,317 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:17:55,317 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:21:23,527 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-22 14:21:23,527 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-22 14:21:23,528 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-22 14:21:23,528 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:21:23,528 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-22 14:21:23,528 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 13:25:20,831 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-23 13:25:20,833 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-23 13:25:20,835 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-23 13:25:20,835 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 13:25:20,835 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 13:25:20,835 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:25:52,343 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-23 16:25:52,344 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-23 16:25:52,345 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-23 16:25:52,346 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:25:52,346 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:25:52,346 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:28:03,909 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-23 16:28:03,909 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-23 16:28:03,910 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-23 16:28:03,910 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:28:03,910 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-23 16:28:03,910 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 18:37:01,292 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 18:37:01,294 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 18:37:01,295 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 18:37:01,296 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 18:37:01,296 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 18:37:01,296 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:44:32,417 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 19:44:32,418 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 19:44:32,419 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 19:44:32,419 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:44:32,419 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:44:32,419 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:50:18,948 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 19:50:18,949 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 19:50:18,949 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 19:50:18,949 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:50:18,950 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:50:18,950 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:53:19,752 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 19:53:19,752 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 19:53:19,753 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 19:53:19,753 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:53:19,753 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 19:53:19,753 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:38:09,807 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:38:09,808 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:38:09,808 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:38:09,808 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:38:09,808 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:38:09,809 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:43:43,351 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:43:43,352 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:43:43,352 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:43:43,352 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:43:43,353 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:43:43,353 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:45:41,768 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:45:41,768 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:45:41,769 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:45:41,769 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:45:41,769 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:45:41,770 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:46:06,811 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:46:06,811 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:46:06,812 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:46:06,812 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:46:06,812 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:46:06,812 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:50:30,295 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:50:30,295 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:50:30,296 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:50:30,296 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:50:30,296 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:50:30,296 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:57:52,603 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-05-29 20:57:52,603 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-05-29 20:57:52,604 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-05-29 20:57:52,604 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:57:52,604 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-05-29 20:57:52,604 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-06-02 10:05:53,280 INFO: 用户数据库初始化成功: database.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:105]
2025-06-02 10:05:53,282 INFO: 实验数据库初始化成功: database2.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:132]
2025-06-02 10:05:53,283 INFO: 注意力测验数据库初始化成功: database3.db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:158]
2025-06-02 10:05:53,284 INFO: 数据库连接正常: user_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-06-02 10:05:53,284 INFO: 数据库连接正常: experiment_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
2025-06-02 10:05:53,284 INFO: 数据库连接正常: attention_db [in C:\Users\21502\PycharmProjects\PythonProject3\Back_end.py:421]
